# Generated by Django 4.0.4 on 2022-05-01 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_profile_owner_alter_examanswer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='owner',
            new_name='user',
        ),
    ]
