# Generated by Django 4.0.4 on 2022-05-07 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.profile'),
        ),
    ]
